spring.application.name=tech-test-app

spring.security.user.name=user
spring.security.user.password=p455word
spring.security.user.roles=ADMIN,USER

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

